apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-username: YnJpbGxpYW4=
  mongo-password: bGVub3Zv
  MONGO_URI: bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvZGFya3Jvb20/YXV0aFNvdXJjZT13cml0ZWFwcCZ3PTE=