apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports: 
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      # env:
      #   - name: MONGO_INITDB_ROOT_USERNAME
      #     valueFrom:
      #       secretKeyRef:
      #         name: mongodb-secret
      #         key: mongo-username
      #   - name: MONGO_INITDB_ROOT_PASSWORD
      #     valueFrom:
      #       secretKeyRef:
      #         name: mongodb-secret
      #         key: mongo-password
      #   - name: ME_CONFIG_MONGODB_SERVER  
      #     valueFrom:
      #       configMapKeyRef:
      #         name: mongo-configmap
      #         key: database_url

      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongo-volume


    


---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 31020
  
